<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bbd3eec6-1f2e-42df-9343-b15cbb720f59</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketValidator.Application\TicketValidator.Application.csproj" />
    <ProjectReference Include="..\TicketValidator.Infrastructure\TicketValidator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
